# metrics_api/llm_provider.py

from __future__ import annotations

import time
from abc import ABC, abstractmethod

from langsmith import traceable
from openai import OpenAI


class AbstractLLMProvider(ABC):
    @abstractmethod
    def generate(self, prompt: str) -> str:
        raise NotImplementedError


class OpenAILLMProvider(AbstractLLMProvider):
    def __init__(
        self,
        model: str = "gpt-4o-mini",
        timeout_seconds: float = 20.0,
        max_retries: int = 2,
    ) -> None:
        self.client = OpenAI(timeout=timeout_seconds)
        self.model = model
        self.max_retries = max_retries

    @traceable(name="openai_generate_station_summary", run_type="llm")
    def generate(self, prompt: str) -> str:
        last_error: Exception | None = None

        for attempt in range(self.max_retries + 1):
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are an industrial compressed-air monitoring assistant. "
                                "Return concise, factual operational summaries. "
                                "Do not invent data. "
                                "Use only the provided metrics "
                                "and quality report."
                            ),
                        },
                        {
                            "role": "user",
                            "content": prompt,
                        },
                    ],
                    temperature=0.2,
                )

                content = response.choices[0].message.content

                if not content:
                    raise RuntimeError("LLM returned an empty response")

                return content.strip()

            except Exception as error:
                last_error = error

                if attempt >= self.max_retries:
                    break

                time.sleep(2**attempt)

        raise RuntimeError(f"LLM provider failed: {last_error}") from last_error


class FakeLLMProvider(AbstractLLMProvider):
    def generate(self, prompt: str) -> str:
        return "Station summary generated by fake test provider."